### ISSUE TITLE
Change storage at runtime

### ISSUE THREAD

**Issue by Sonic198** [gottscj/Hangfire.Mongo#391]
Hello,

I'm trying to change storage at runtime. My intention is to remove a need of restarting application when user/password needs to be updated. I'm monitoring connection string in my `appsettings.json` file and whenever change occurs then `IOptionsMonito.OnChange` method is called, inside which I'm calling `GlobalConfiguration.Configuration.UseMongoStorage(...)`. For testing purposes I was switching between databases (`mongodb://localhost:27017/db --> mongodb://localhost:27017/db1`) to see if that case would be also working. But even though hangfire collections are created in new DB it seem like hangfire server is still connecting to old DB as well as dashboard.

Is it even possible to change storage at runtime?

Here is my setup:

```csharp
public static IServiceCollection AddHangfire(
    this IServiceCollection services,
    IConfiguration configuration)
{
    ParameterCheckHelper.NullCheck(() => services, () => configuration);

    services.AddSingleton<ITimeZoneResolver, TimeZoneResolver>();
    services.AddHangfireServer(x =>
    {
        x.WorkerCount = 1;
        x.Queues = "default";
    });

    services.AddHangfire((sp, config) =>
    {
        var storageOptions = new MongoStorageOptions
        {
            MigrationOptions = new MongoMigrationOptions
            {
                MigrationStrategy = new DropMongoMigrationStrategy(),
                BackupStrategy = new NoneMongoBackupStrategy()
            },
            CheckConnection = false
        };

        var mongoDB = sp.GetRequiredService<IMongoClientManager>();
        var connectionStringsMonitor = sp.GetRequiredService<IOptionsMonitor<ConnectionStrings>>();
        connectionStringsMonitor.OnChange(_ =>
        {
            //whenever conn str change occurs then new IMongoClient and IMongoDatabase is referenced from  IMongoClientManager
            GlobalConfiguration.Configuration.UseMongoStorage(mongoDB.Client, mongoDB.Database.DatabaseNamespace.DatabaseName, storageOptions);                
        });

        config.SetDataCompatibilityLevel(CompatibilityLevel.Version_170)
            .UseSimpleAssemblyNameTypeSerializer()
            .UseRecommendedSerializerSettings()
            .UseMongoStorage(
                mongoDB.Client,
                mongoDB.Database.DatabaseNamespace.DatabaseName,
                storageOptions);
            
        config.UseSerilogLogProvider();
        config.UseFilter(new PreserveOriginalQueueAttribute());
    });

    GlobalJobFilters.Filters.Add(new AutomaticRetryAttribute { Attempts = 1 });

    return services;
}

...

public static IApplicationBuilder UseHangfire(this WebApplication app)
{
    ParameterCheckHelper.NullCheck(() => app);

    app.UseHangfireDashboard(
        "/hangfire",
        new DashboardOptions
        {
            IsReadOnlyFunc = _ => true,
            AppPath = "/swagger",
            TimeZoneResolver = app.Services.GetRequiredService<ITimeZoneResolver>(),
            Authorization = [new AllowAllAuthorizationFilter()]
        });

    return app;
}
```

**Comment by gottscj** [comment]
@Sonic198,

Im pretty sure you need to
1. Stop Hangfire server
2. Start Hangfire Server again with new connectionString. I dont think its supported to change storage while Hangfire is running.

You would have to check with @odinserj, who is the owner of Hangfire.

Please be advised any jobs scheduled to run on the old db will be left orphaned. 
Would it be possible to have a separate dedicated db for hangfire?

I hope this helps.

**Comment by Sonic198** [comment]
@gottscj Thank you for your response, even if you would have dedicated DB you still need to change password for your DB user. That is my main purpose of this question. 

Can I stop and start server programmatically?

**Comment by gottscj** [comment]
@Sonic198,

I would start by looking into how the extensions methods work. Also you might need completely create a new Hangfire instance. 
I dont know.

check out:
https://github.com/HangfireIO/Hangfire/blob/main/samples/ConsoleSample/Program.cs
https://docs.hangfire.io/en/latest/background-processing/processing-jobs-in-console-app.html

If you can accept the downtime, would it not be easier to restart the application as a whole with the new settings?

**Comment by gottscj** [comment]
@Sonic198,

Did it work out for you?

Thanks

**Comment by Sonic198** [comment]
Unfortunately no, since I'm using Asp.Net Core hangfire is starting hosted service in the backgroud which I would need to write in some other way because even if I could stop/start hosted service which should in theory create new hangfire procesing server instance, for some reason JobStorage service was returning wrong instance even if I unregister it and register my own implementation. I can't explain it why... so I simply gave up with this and will probably convert that piece of code into AWS lambda.

**Comment by gottscj** [comment]
ok. closing.

Good luck!
