### ISSUE TITLE
Migration fails on schema downgrade even for a DropMongoMigrationStrategy()

### ISSUE THREAD

**Issue by MattA48** [gottscj/Hangfire.Mongo#393]
Hi,

This may well be WorkingAsIntended but we see the drop migration strategy fail with an InvalidOperationException due to a schema downgrade.

I understand the downgrade issue for true migrations, but isn't this a bit overkill for the Drop strategy? Unless there's concern that there will be a new collection in the new schema that's missed off.

**Comment by gottscj** [comment]
@MattA48,

I see your point. 
I will try to get it done to next release.

Thanks!

**Comment by gottscj** [comment]
@MattA48 
Should be supported in the latest release. let me know if it works for you. :)

**Comment by gottscj** [comment]
sure thing. I will close this, you can open it again if you encounter issues
