### ISSUE TITLE
Unable to run .net core application with Hangfire and Cosmos DB (Mongo Db)

### ISSUE THREAD

**Issue by harishrathi** [gottscj/Hangfire.Mongo#402]
I am using Hangfire and Cosmos DB (Mongo Db). Getting exactly same error as #259. Below is my setup:

>
>     <PackageReference Include="MongoDB.Driver" Version="2.26.0" />
>     <PackageReference Include="Hangfire.AspNetCore" Version="1.8.10" />
>     <PackageReference Include="Hangfire.Mongo" Version="1.10.7" />
>     <PackageReference Include="Microsoft.Azure.Cosmos" Version="3.41.0" />
> 

And the code

```
        var storageOptions = new MongoStorageOptions
        {
            MigrationOptions = new MongoMigrationOptions
            {
                MigrationStrategy = new DropMongoMigrationStrategy(),
                BackupStrategy = new NoneMongoBackupStrategy()
            },
            Prefix = "hgf",
        };

        services.AddHangfire((provider, config) =>
        {
            config
            .SetDataCompatibilityLevel(CompatibilityLevel.Version_180)
            .UseSimpleAssemblyNameTypeSerializer()
            .UseRecommendedSerializerSettings()            
            .UseMongoStorage(connStr.MongoDb, DatabaseConfigurator.MongoDatabaseName, storageOptions)
            .UseConsole();
        });

        services.AddHangfireServer();
```

The error I am getting is: 

> Hangfire.Mongo.Migration.MongoMigrationException: Migration failed in Hangfire.Mongo.Migration.Steps.Version09.CreateSignalCollection
>  ---> MongoDB.Driver.MongoCommandException: Command create failed: Capped collectiosn are not supported..
>    at MongoDB.Driver.Core.WireProtocol.CommandUsingCommandMessageWireProtocol`1.ProcessResponse(ConnectionId connectionId, CommandMessage responseMessage)
............................
>    at Hangfire.Mongo.Migration.Steps.Version09.CreateSignalCollection.Execute(IMongoDatabase database, MongoStorageOptions storageOptions, IMongoMigrationContext migrationContext)
>    at Hangfire.Mongo.Migration.Strategies.MongoMigrationStrategy.ExecuteMigration(IMongoDatabase database, MongoSchema fromSchema, MongoSchema toSchema)
>    --- End of inner exception stack trace ---
>    at Hangfire.Mongo.Migration.Strategies.MongoMigrationStrategy.ExecuteMigration(IMongoDatabase database, MongoSchema fromSchema, MongoSchema toSchema)
>    at Hangfire.Mongo.Migration.Strategies.DropMongoMigrationStrategy.ExecuteMigration(IMongoDatabase database, MongoSchema fromSchema, MongoSchema toSchema)
>    at Hangfire.Mongo.Migration.Strategies.MongoMigrationStrategy.Execute(MongoStorageOptions storageOptions, IMongoDatabase database, MongoSchema fromSchema, MongoSchema toSchema)
>    at Hangfire.Mongo.Migration.MongoMigrationManager.MigrateUp()
>    at Hangfire.Mongo.MongoStorage..ctor(IMongoClient mongoClient, String databaseName, MongoStorageOptions storageOptions)
>    at Hangfire.Mongo.MongoStorage..ctor(MongoClientSettings mongoClientSettings, String databaseName, MongoStorageOptions storageOptions)
>    at Hangfire.Mongo.MongoBootstrapperConfigurationExtensions.UseMongoStorage(IGlobalConfiguration configuration, MongoClientSettings mongoClientSettings, String databaseName, MongoStorageOptions storageOptions)
>    at Hangfire.Mongo.MongoBootstrapperConfigurationExtensions.UseMongoStorage(IGlobalConfiguration configuration, String connectionString, String databaseName, MongoStorageOptions storageOptions)
>    at TradeAstra.ServerApi.Configurators.HangfireConfigurator.<>c__DisplayClass0_0.<AddHangfireTasks>b__0(IServiceProvider provider, IGlobalConfiguration config) in C:\Users\haris\Documents\GitHub\ast-trader\TradeAstra.ServerApi\Configurators\HangfireConfigurator.cs:line 28
>    at Hangfire.HangfireServiceCollectionExtensions.<>c__DisplayClass1_0.<AddHangfire>b__14(IServiceProvider serviceProvider) in C:\projects\hangfire-525\src\Hangfire.NetCore\HangfireServiceCollectionExtensions.cs:line 103
>

So basically, I need to disable capped collection, but cannot find anything on how to do it?

**Comment by harishrathi** [comment]
sorry I set `SupportsCappedCollection = false` and it moved ahead

**Comment by harishrathi** [comment]
for the same setup, now getting another error saying cannot modify 


> Hangfire.Mongo.Migration.MongoMigrationException: Migration failed in Hangfire.Mongo.Migration.Steps.Version15.CreateUniqueLockIndex
>  ---> MongoDB.Driver.MongoCommandException: Command createIndexes failed: Error=13, Details='Response status code does not indicate success: Forbidden (403); Substatus: 0; ActivityId: d0b43a64-1964-42e4-9854-d612e167181f; Reason: (Message: {"Errors":["The unique index cannot be modified. To change the unique index, remove the collection and re-create a new one."]}
> ..........
>  ResourceType: Collection, OperationType: Replace
> , SDK: Microsoft.Azure.Documents.Common/2.14.0, Microsoft.Azure.Cosmos.Tracing.TraceData.ClientSideRequestStatisticsTraceDatum, Windows/10.0.20348 cosmos-netstandard-sdk/3.18.0);.
>    at MongoDB.Driver.Core.WireProtocol.CommandUsingCommandMessageWireProtocol`1.ProcessResponse(ConnectionId connectionId, CommandMessage responseMessage)
>    at MongoDB.Driver.Core.WireProtocol.CommandUsingCommandMessageWireProtocol`1.SendMessageAndProcessResponse(CommandRequestMessage message, Int32 responseTo, IConnection connection, CancellationToken cancellationToken)
>    at MongoDB.Driver.Core.WireProtocol.CommandUsingCommandMessageWireProtocol`1.Execute(IConnection connection, CancellationToken cancellationToken)
>    at MongoDB.Driver.Core.Servers.Server.ServerChannel.ExecuteProtocol[TResult](IWireProtocol`1 protocol, ICoreSession session, CancellationToken cancellationToken)
> ............
>    at Hangfire.Mongo.Migration.Steps.Version15.CreateUniqueLockIndex.Execute(IMongoDatabase database, MongoStorageOptions storageOptions, IMongoMigrationContext migrationContext)
>    at Hangfire.Mongo.Migration.Strategies.MongoMigrationStrategy.ExecuteMigration(IMongoDatabase database, MongoSchema fromSchema, MongoSchema toSchema)
>    --- End of inner exception stack trace ---
>    at Hangfire.Mongo.Migration.Strategies.MongoMigrationStrategy.ExecuteMigration(IMongoDatabase database, MongoSchema fromSchema, MongoSchema toSchema)
>

**Comment by gottscj** [comment]
@harishrathi,

I haven't been very good at updating the readme file.
there is a dedicated CosmosStorage which is set to use the configuration needed to use cosmosdb. its not very well tested as I haven't got an actual cosmosdb instance to test on.

You should use the "UseCosmosStorage" extension and the "CosmosStorageOptions"

check out:
https://github.com/gottscj/Hangfire.Mongo/blob/master/src/Hangfire.Mongo.Sample.CosmosDB/Startup.cs

I will make sure to update the readme asasp.

let me know if it works out for you.

Thanks!

**Comment by harishrathi** [comment]
It still failed.. somehow its trying to increase thruput..

> Hangfire.Mongo.Migration.MongoMigrationException: Migration failed in Hangfire.Mongo.Migration.Steps.Version05.CreateJobIdIndex
>  ---> MongoDB.Driver.MongoCommandException: Command createIndexes failed: Error=2, Details='Response status code does not indicate success: BadRequest (400); Substatus: 1028; ActivityId: 34df61d3-fe2b-492c-ab32-6b108a731888; Reason: (Message: {"Errors":["Your account is currently configured with a total throughput limit of 1000 RU\/s. This operation failed because it would have increased the total throughput to 1200 RU\/s. See https:\/\/aka.ms\/cosmos-tp-limit for more information."]}
> ActivityId: 34df61d3-fe2b-492c-ab32-6b108a731888, Request URI: /apps/fb304e99-2781-4c37-bea1-a6714db49a67/services/8c6e34e2-ebd5-48d2-8592-8f4aec6d82a6/partitions/90c6d7b1-feb4-4372-bd49-aa3774fb50e9/replicas/133631730027598053p, RequestStats: , SDK: Microsoft.Azure.Documents.Common/2.14.0, Microsoft.Azure.Cosmos.Tracing.TraceData.ClientSideRequestStatisticsTraceDatum, Windows/10.0.20348 cosmos-netstandard-sdk/3.18.0);.
> 

And the relevant stack-trace

> at MongoDB.Driver.Core.WireProtocol.CommandUsingCommandMessageWireProtocol`1.ProcessResponse(ConnectionId connectionId, CommandMessage responseMessage)
>    at MongoDB.Driver.Core.WireProtocol.CommandUsingCommandMessageWireProtocol`1.SendMessageAndProcessResponse(CommandRequestMessage message, Int32 responseTo, IConnection connection, CancellationToken cancellationToken)
>    at MongoDB.Driver.Core.WireProtocol.CommandUsingCommandMessageWireProtocol`1.Execute(IConnection connection, CancellationToken cancellationToken)
>    at MongoDB.Driver.Core.WireProtocol.CommandWireProtocol`1.Execute(IConnection connection, CancellationToken cancellationToken)
>    at MongoDB.Driver.Core.Servers.Server.ServerChannel.ExecuteProtocol[TResult](IWireProtocol`1 protocol, ICoreSession session, CancellationToken cancellationToken)
>    at MongoDB.Driver.Core.Servers.Server.ServerChannel.Command[TResult](ICoreSession session, ReadPreference readPreference, DatabaseNamespace databaseNamespace, BsonDocument command, IEnumerable`1 commandPayloads, IElementNameValidator commandValidator, BsonDocument additionalOptions, Action`1 postWriteAction, CommandResponseHandling responseHandling, IBsonSerializer`1 resultSerializer, MessageEncoderSettings messageEncoderSettings, CancellationToken cancellationToken)
>    at MongoDB.Driver.Core.Operations.CommandOperationBase`1.ExecuteProtocol(IChannelHandle channel, ICoreSessionHandle session, ReadPreference readPreference, CancellationToken cancellationToken)
>    at MongoDB.Driver.Core.Operations.CommandOperationBase`1.ExecuteProtocol(IChannelSource channelSource, ICoreSessionHandle session, ReadPreference readPreference, CancellationToken cancellationToken)
>    at MongoDB.Driver.Core.Operations.WriteCommandOperation`1.Execute(IWriteBinding binding, CancellationToken cancellationToken)
>    at MongoDB.Driver.Core.Operations.CreateIndexesOperation.Execute(IWriteBinding binding, CancellationToken cancellationToken)
>    at MongoDB.Driver.OperationExecutor.ExecuteWriteOperation[TResult](IWriteBinding binding, IWriteOperation`1 operation, CancellationToken cancellationToken)
>    at MongoDB.Driver.MongoCollectionImpl`1.ExecuteWriteOperation[TResult](IClientSessionHandle session, IWriteOperation`1 operation, CancellationToken cancellationToken)
>    at MongoDB.Driver.MongoCollectionImpl`1.MongoIndexManager.CreateMany(IClientSessionHandle session, IEnumerable`1 models, CreateManyIndexesOptions options, CancellationToken cancellationToken)
>    at MongoDB.Driver.MongoCollectionImpl`1.MongoIndexManager.<>c__DisplayClass9_0.<CreateMany>b__0(IClientSessionHandle session)
>    at MongoDB.Driver.MongoCollectionImpl`1.UsingImplicitSession[TResult](Func`2 func, CancellationToken cancellationToken)
>    at MongoDB.Driver.MongoCollectionImpl`1.MongoIndexManager.CreateMany(IEnumerable`1 models, CreateManyIndexesOptions options, CancellationToken cancellationToken)
>    at MongoDB.Driver.MongoCollectionImpl`1.MongoIndexManager.CreateMany(IEnumerable`1 models, CancellationToken cancellationToken)
>    at Hangfire.Mongo.Migration.IndexMigration.CreateIndexes(IMongoCollection`1 collection, Func`2 getIndexType, String[] indexNames, Func`2 createOptions)
>    at Hangfire.Mongo.Migration.IndexMigration.TryCreateIndexes(IMongoCollection`1 collection, Func`2 indexType, String[] indexNames)
>    at Hangfire.Mongo.Migration.Steps.Version05.CreateJobIdIndex.Execute(IMongoDatabase database, MongoStorageOptions storageOptions, IMongoMigrationContext migrationContext)
>    at Hangfire.Mongo.Migration.Strategies.MongoMigrationStrategy.ExecuteMigration(IMongoDatabase database, MongoSchema fromSchema, MongoSchema toSchema)
>    --- End of inner exception stack trace ---
>    at Hangfire.Mongo.Migration.Strategies.MongoMigrationStrategy.ExecuteMigration(IMongoDatabase database, MongoSchema fromSchema, MongoSchema toSchema)
>    at Hangfire.Mongo.Migration.Strategies.DropMongoMigrationStrategy.ExecuteMigration(IMongoDatabase database, MongoSchema fromSchema, MongoSchema toSchema)
>    at Hangfire.Mongo.Migration.Strategies.MongoMigrationStrategy.Execute(MongoStorageOptions storageOptions, IMongoDatabase database, MongoSchema fromSchema, MongoSchema toSchema)
>    at Hangfire.Mongo.Migration.MongoMigrationManager.MigrateUp()
>    at Hangfire.Mongo.MongoStorage..ctor(IMongoClient mongoClient, String databaseName, MongoStorageOptions storageOptions)
>    at Hangfire.Mongo.CosmosDB.CosmosStorage..ctor(IMongoClient mongoClient, String databaseName, CosmosStorageOptions storageOptions)
>    at Hangfire.Mongo.CosmosDB.CosmosBootstrapperConfigurationExtensions.UseCosmosStorage(IGlobalConfiguration configuration, IMongoClient mongoClient, String databaseName, CosmosStorageOptions storageOptions)
>    at TradeAstra.ServerApi.Configurators.HangfireConfigurator.<>c__DisplayClass1_0.<ConfigureAndAddHangfireCosmos4MongoDb>b__0(IGlobalConfiguration config) in C:\Users\haris\Documents\GitHub\ast-trader\TradeAstra.ServerApi\Configurators\HangfireConfigurator.cs:line 55
>    at Hangfire.HangfireServiceCollectionExtensions.<>c__DisplayClass0_0.<AddHangfire>b__0(IServiceProvider provider, IGlobalConfiguration config) in C:\projects\hangfire-525\src\Hangfire.NetCore\HangfireServiceCollectionExtensions.cs:line 40
>    at Hangfire.HangfireServiceCollectionExtensions.<>c__DisplayClass1_0.<AddHangfire>b__14(IServiceProvider serviceProvider) in C:\projects\hangfire-525\src\Hangfire.NetCore\HangfireServiceCollectionExtensions.cs:line 103
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
>    at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(ServiceIdentifier serviceIdentifier)
>    at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
>    at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
>    at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
>    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
>    at Hangfire.HangfireServiceCollectionExtensions.ThrowIfNotConfigured(IServiceProvider serviceProvider) in C:\projects\hangfire-525\src\Hangfire.NetCore\HangfireServiceCollectionExtensions.cs:line 307
>

**Comment by harishrathi** [comment]
I tried increasing the throughput from 1000 to 2000 and then to 3000... but it keeps asking for more. I cannot make it unlimited as it might increase the cost drastically. I dont think problem is the throughput limit.. its something else.

**Comment by gottscj** [comment]
@harishrathi,

The initial migration is quite chatty, so there will be a spike on the Request Unit balance. You could try to write your own MigrationStrategy which overrides "ExectuteMigration" method and add a 1s delay delay between migration steps. This should limit the RU/s. worth trying out

https://github.com/gottscj/Hangfire.Mongo/blob/master/src/Hangfire.Mongo/Migration/Strategies/MongoMigrationStrategy.cs

When the migration is done the throughput will be a function of how many jobs you have and would not need the high throughput.

**Comment by gottscj** [comment]
@harishrathi,

did you find a resolution to this? It might help others facing the same issues.

Thanks!

**Comment by harishrathi** [comment]
nope.. I did not found any resolution. I have moved back to SQL Server...

Thanks for the help!

**Comment by varempty** [comment]
When I use MongoDB When Driver Version 2.28 was notified of GlobalConfiguration Configuration. UseMongoStore is not supported,Thank you for any help
