### ISSUE TITLE
Assembly version doesn't match nuget version.

### ISSUE THREAD

**Issue by tea-mike** [gottscj/Hangfire.Mongo#407]
Can the assembly versions get updated to match the nuget version?

For example, in master, the assembly version is still specified as 0.7.28

[assembly: AssemblyVersion("0.7.28")]
[assembly: AssemblyFileVersion("0.7.28")]
[assembly: AssemblyInformationalVersion("0.7.28")]

**Comment by gottscj** [comment]
Fixed with 1.10.0 release.
