### ISSUE TITLE
DropMongoMigrationStrategy actual vs documented behaviour.

### ISSUE THREAD

**Issue by Vladimir-Frolov** [gottscj/Hangfire.Mongo#412]
Hello,

Regarding DropMongoMigrationStrategy docs says that this strategy will drop the database:
```
Drop

This will simply just drop your existing Hangfire.Mongo database and update the schema version. 
No fuzz and ready to start from scratch. It is the perfect strategy if you e.g. enque all your jobs at startup.
```

But if we look at the code, it looks like that this strategy has never droped the entire database, but hangfire collections only.

Could you please clarify the behaviour of this strategy? Is it required to have a separate mongo database for hangfire.mongo? Are the any plans on changing the behaviour of this strategy in future releases (e.g. it will drop the entire database including hangfire collections and other collection persisted in the db)?

Best regards,
Vladimir

**Comment by gottscj** [comment]
@Vladimir-Frolov,

I dont recall exactly why we opted for dropping the collections only. probably a combination of.
- It might not be a hangfire specific database, so users might unintentionally drop their application database.
- Dropping the database might require admin rights. I dont recall.
- The time the migration runs. We are already connected to the database. dropping it entirely would require use to re-connect to the database.
- Its not needed as dropping all collections gives the same end result.
- 
We don't plan to change the current supported strategies. We have hopefully created a design where users of the lib can write their own strategies if needed.
It is not required to have a separate database.
I will update the documentation to describe this better. Thanks for the feedback!

I hope this helps!

Thanks!

**Comment by Vladimir-Frolov** [comment]
@gottscj 

Yes, it really helps. 
Thanks for quick response!

Best regards,
Vladimir
